---

- name: Manage VM
  hosts: localhost
  vars:
    validate_certs: false
    cmdb_url: http://localhost:8080
    ipam_url: http://localhost:8081
  tasks:

    - name: manage git repository
      ansible.builtin.include_tasks: 
        file: tasks/git-tasks.yaml   
      vars:
        repo_url: "{{ repo_url }}"
        repo_dir: "{{ repo_dir }}"
        repo_branch: "{{ repo_branch }}"
        task_name: git-pull

    - name: Include vars of vars.yaml into the 'vm_vars' variable.
      ansible.builtin.include_vars:
        file: "{{ repo_dir }}/vars.yaml"
        name: vm_vars

    - name: manage VMs
      ansible.builtin.include_tasks: tasks/configure-vm.yaml
      loop: "{{ vm_vars.virtualMachines }}"
      loop_control:
        label: "{{ vm.vm_name }}"
        loop_var: vm

    - name: Check if any VM manifests have changed
      ansible.builtin.shell: "git status --porcelain"
      args:
        chdir: "{{ repo_dir }}"
      register: git_status
      changed_when: false

    - name: Find manifest files
      ansible.builtin.find:
        paths: "{{ repo_dir }}"
        patterns: '*.yaml'
        excludes: 
          - 'kustomization.yaml'
          - 'vars.yaml'
      register: found_files

    - name: Store paths in a simple flat list
      ansible.builtin.set_fact:
        files_list: "{{ found_files.files | map(attribute='path') | map('basename') | list }}"

    - name: Update Kustomization file
      ansible.builtin.template:
        src: templates/kustomization.yaml.j2
        dest: "{{ repo_dir }}/kustomization.yaml"

    - name: Commit commit and push changes
      ansible.builtin.include_tasks: 
        file: tasks/git-tasks.yaml
      vars:
        task_name: git-commit
      when: git_status.stdout | length > 0
