- name: Manage VM
  hosts: localhost
  tasks:

    - name: Diff Two YAML Data Structures
      hosts: localhost
      gather_facts: false
      tasks:
        - name: Load content of first YAML file
          ansible.builtin.include_vars:
            file: manifests/my-test-vm.yaml
            name: my-test-vm_data

        - name: Load content of second YAML file
          ansible.builtin.include_vars:
            file: manifests/test-vm2.yaml
            name: test-vm2_data

        - name: Compare the structural data
          ansible.utils.fact_diff:
            before: "{{ my-test-vm_data }}"
            after: "{{ test-vm2_data }}"
          register: yaml_diff