---

- name: get current VM state
  redhat.openshift_virtualization.kubevirt_vm_info:
    name: "{{ item.vm_name }}"
    namespace: "{{ vm_vars.namespace }}"
  register: vm_info

- name: set vm_exists fact
  ansible.builtin.set_fact:
    vm_exists: "{{ vm_info.resources | length > 0 | bool }}"

- name: create new VM resources
  block:
    - name: create cmdb record
      ansible.builtin.uri:
        url: "{{ cmdb_url }}/vm/create"
        method: POST
        status_code: 201
      register: new_cmdb_record_response

    - name: set cmdb uuid fact
      ansible.builtin.set_fact:
        cmdb_uuid: "{{ new_cmdb_record_response.json.resource_UUID }}"
  when: not vm_exists
  
- name: get info from existing VM
  block:
    - name: set cmdb annotation fact
      ansible.builtin.set_fact:
        cmdb_uuid: "{{ vm_info.resources[0].metadata.annotations.cmdb }}"
  when: vm_exists
  


- name: update vm manifest
  ansible.builtin.set_fact:
    vm_manifest: "{{ lookup('ansible.builtin.template', 'templates/virtualmachine.yaml.j2') }}"
  vars:
    vm: "{{ item }}"
    vm_namespace: "{{ vm_vars.namespace }}"

- name: create vm manifest
  ansible.builtin.copy:
    content: "{{ vm_manifest }}"
    dest: "{{ item.vm_name }}.yaml"
  when: item.state | default('present') == 'present'
  delegate_to: localhost

- name: create vm manifest
  ansible.builtin.copy:
    content: "{{ vm_manifest }}"
    dest: "{{ item.vm_name }}.yaml"
  when: item.state | default('present') == 'present'
  delegate_to: localhost

# - name: delete vm manifest
#   ansible.builtin.file:
#     path: "{{ item.vm_name }}.yaml"
#     state: absent
#   when: item.state | default('present') == 'absent'


# - name: Create or update virtual machine
#   redhat.openshift.k8s:
#     state: present
#     template: templates/virtualmachine.yaml.j2
#     validate_certs: "{{ validate_certs }}"
#   vars:
#     vm: "{{ item }}"
#     vm_namespace: "{{ vm_vars.namespace }}"
#   when: item.state | default('present') == 'present'

# - name: Delete virtual machine
#   redhat.openshift.k8s:
#     state: absent
#     api_version: kubevirt.io/v1
#     kind: VirtualMachine
#     name: "{{ item.vm_name }}"
#     namespace: "{{ vm_vars.namespace }}"
#     validate_certs: "{{ validate_certs }}"
#   when: item.state | default('present') == 'absent'
