---
- name: Render and apply Metadata ConfigMap
  block:
    - name: Render Metadata ConfigMap manifest
      ansible.builtin.template:
        src: templates/metadata-configmap.yaml.j2
        dest: "{{ configmap_path }}"
      vars:
        cmdb_uuid: "{{ cmdb_uuid }}"

    - name: Update Metadata ConfigMap resource
      redhat.openshift.k8s:
        state: "{{ manifest_state }}"
        src: "{{ configmap_path }}"
  when: manifest_state == "present"

- name: Delete Metadata ConfigMap
  block:
    - name: Delete Metadata ConfigMap resource
      redhat.openshift.k8s:
        state: absent
        kind: ConfigMap
        name: "{{ vm.vm_name }}-metadata"
        namespace: "{{ vm_vars.namespace }}"

    - name: Delete Metadata ConfigMap manifest
      ansible.builtin.file:
        path: "{{ configmap_path }}"
        state: absent
  when: manifest_state == "absent"
