- name: Pull git repository
  block:
    - name: Verify if the directory exists
      ansible.builtin.stat:
        path: "{{ repo_dir }}"
      register: dir_status

    ## TODO add handling for empty repo
    - name: Clone git repository
      ansible.builtin.command:
        cmd: "git clone {{ repo_url }} {{ repo_dir }}"
      changed_when: false
      when: not dir_status.stat.exists

    - name: Pull git repository
      ansible.builtin.command:
        cmd: "git pull"
        chdir: "{{ repo_dir }}"
      when: dir_status.stat.exists
  when: task_name == 'git-pull'

- name: Commit and push changes
  block:
    - name: Stage changes
      ansible.builtin.command:
        cmd: "git add ."
        chdir: "{{ repo_dir }}"
    - name: Commit changes
      ansible.builtin.command:
        cmd: "git commit -am 'Updated VM config'"
        chdir: "{{ repo_dir }}"
    - name: Push changes
      ansible.builtin.command:
        cmd: "git push"
        chdir: "{{ repo_dir }}"
  when: task_name == 'git-commit'