---

- name: Manage VM
  hosts: localhost
  vars:
    validate_certs: false
    cmdb_url: http://localhost:8080
    ipam_url: http://localhost:8081
  tasks:

    - name: Clone git repository
      ansible.builtin.include_role:
        name: git
        tasks_from: git-clone.yaml
      tags:
        - git
        - git-clone

    - name: Include vars of vars.yaml into the 'vm_vars' variable.
      ansible.builtin.include_vars:
        file: "{{ repo_dir }}/vars.yaml"
        name: vm_vars

    - name: manage VMs
      ansible.builtin.include_tasks: tasks/configure-vm.yaml
      loop: "{{ vm_vars.virtualMachines }}"
      loop_control:
        label: "{{ vm.vm_name }}"
        loop_var: vm

    - name: Check if any VM manifests have changed
      ansible.builtin.shell: "git status --porcelain"
      args:
        chdir: "{{ repo_dir }}"
      register: git_status
      changed_when: false
      tags:
        - git

    - name: Commit and push changes
      ansible.builtin.include_tasks: 
        file: roles/git/tasks/git-commit.yaml
      when: git_status.stdout | length > 0
      tags:
        - git
        - git-commit
